package com.azid.auth.backend.AZ.Auth.model;

import java.util.UUID;

import jakarta.persistence.*;

@Entity
@Table(name = "users") // Use "users" or another non-reserved name
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, nullable = false)
    private String userId; // Autogenerated unique userId

    private String username;

    @Column(unique = true)
    private String email;

    private String password;

    private String role; // e.g., ROLE_USER

    private String idType; // Identification type, e.g., NRIC

    @Column(unique = true, nullable = false)
    private String idNo; // Identification number, e.g., "101010-12-3456"

    private String mobileNoPrefix; // Mobile number prefix, e.g., "60"

    @Column(nullable = false)
    private String mobileNo; // Mobile number, e.g., "123456789"


    // Constructor for generating userId
    public User() {
        this.userId = UUID.randomUUID().toString(); // Automatically generates a unique userId
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getIdNo() {
        return idNo;
    }

    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }

    public String getIdType() {
        return idType;
    }

    public void setIdType(String idType) {
        this.idType = idType;
    }

    public String getMobileNoPrefix() {
        return mobileNoPrefix;
    }

    public void setMobileNoPrefix(String mobileNoPrefix) {
        this.mobileNoPrefix = mobileNoPrefix;
    }

    public String getMobileNo() {
        return mobileNo;
    }

    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
}