package com.azid.auth.backend.AZ.Auth.model;

import java.util.UUID;
import jakarta.persistence.*;

@Entity
@Table(name = "users") // Use "users" or another non-reserved name
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, nullable = false)
    private String userId; // Autogenerated unique userId

    private String username;

    @Column(unique = true)
    private String email;

    private String password;

    private String role; // e.g., ROLE_USER

    // Constructor for generating userId
    public User() {
        this.userId = UUID.randomUUID().toString(); // Automatically generates a unique userId
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
