package com.azid.auth.backend.AZ.Auth.model;

import java.util.UUID;

import jakarta.persistence.*;
import lombok.Data;

@Entity
@Table(name = "users") // Use "users" or another non-reserved name
@Data
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, nullable = false)
    private String userId; // Autogenerated unique userId

    @Column(nullable = false)
    private String username;

    @Column(unique = true, nullable = false)
    private String email;

    @Column(nullable = false)
    private String password;

    private String role; // e.g., ROLE_USER

    @Column(nullable = false)
    private String idType; // Identification type, e.g., NRIC

    @Column(unique = true, nullable = false)
    private String idNo; // Identification number, e.g., "101010-12-3456"

    @Column(nullable = false)
    private String mobileNoPrefix; // Mobile number prefix, e.g., "60"

    @Column(nullable = false)
    private String mobileNo; // Mobile number, e.g., "123456789"

    // Constructor for generating userId
    public User() {
        this.userId = UUID.randomUUID().toString(); // Automatically generates a unique userId
    }
}